name: example
on: [push, workflow_dispatch]

jobs:
    run-with-namespace-cache:
      runs-on:
        # Replace with your profile label https://namespace.so/docs/features/faster-github-actions#using-runner-profiles
        - namespace-profile-amd64-with-caching
      name: Sample with Namespace cache
      steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Set up JDK 17.0
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              architecture: x64
              distribution: 'temurin'

          - name: Set up cache
            uses: namespacelabs/nscloud-cache-action@v1
            with:
              cache: gradle

          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
            with:
              cache-disabled: true
              arguments: build

    run-with-github-cache:
        runs-on:
            - ubuntu-latest
        name: Sample with GitHub cache
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up JDK 17.0
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                architecture: x64
                distribution: 'temurin'
                cache: 'gradle'
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                cache-disabled: true
                arguments: build
